# Server configuration
[server]
host = "localhost"
port = "8080"

# Stage 1: Set a variable for API base URL
[[stages]]
name = "setup"
action = "set_variable"
[stages.parameters]
name = "api_base"
value = "https://libgen.is/search.php?lg_topic=libgen&open=0&view=simple&res=25&phrase=1&column=def"


# Stage 2: GET request to fetch user data
[[stages]]
name = "fetch_search"
action = "get"
[stages.parameters]
url = "{{.variables.api_base}}&req={{.variables.query_term}}"
[stages.parameters.headers]
"User-Agent" = "ActionService/1.0"
"Accept" = "application/json"

# Stage 3: Transform the response to extract specific fields
[[stages]]
name = "extract_first_mirror"
action = "scrape"
[stages.parameters]
input = "stages.fetch_search"
selector = "a"
operation = "filter"
filter_type = "attribute"
attribute = "title"
filter_value = "Libgen"
contains = true

# Stage 4: Get book link
[[stages]]
name = "fetch_book_page"
action = "get"
[stages.parameters]
url = "{{ (index .stages.extract_first_mirror 0).attributes.href }}"

# Stage 5: Find the download link
[[stages]]
name = "find_download_link"
action = "scrape"
[stages.parameters]
input = "stages.fetch_book_page"
selector = "a"
operation = "first"

# Stage 6: Find book name
[[stages]]
name = "find_book_name"
action = "scrape"
[stages.parameters]
input = "stages.fetch_book_page"
selector = "h1"
operation = "first"

# Stage 7: Download the file
[[stages]]
name = "download_book"
action = "download"
[stages.parameters]
url = "{{ .stages.find_download_link.attributes.href }}"
output = "./downloads/{{ .stages.find_book_name.text }}.pdf"

# Setup endpoint
[[stages]]
name = "search_book_api"
action = "api"
[stages.parameters]
path = "/search"
method = "GET"
description = "Fetch user data by ID"