services:
  generic_service:
    container_name: generic_service
    image: ghcr.io/seeya/generic-service:main
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - TZ=Etc/UTC
      - WEBUI_PORT=8998
      - TORRENTING_PORT=6881
    volumes:
      - ./qbittorent:/config
      - ./downloads:/downloads
    ports:
      - 127.0.0.0.1:8998:8998
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
